when:
  - event: manual
  - event: push
    branch: bench/*

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false
      lfs: false

steps:
  - name: Build rivet-truffle
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just build
  - name: Benchmark coremark-nommu
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench-full

  - name: Benchmark coremark-mmu
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench-full --mmu=true
