when:
  - event: manual

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false
      lfs: false

steps:
  - name: build
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just build
  - name: build-coremark
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just build-coremark

  - name: warmup
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench
  - name: bench
    image: bash
    commands:
      - . /etc/profile
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command just bench
